# Generated by Django 5.1.7 on 2025-03-17 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIResumeCheck', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resume',
            new_name='Resume_data',
        ),
        migrations.AlterModelTable(
            name='resume_data',
            table='Resume_datas',
        ),
    ]
